#!/usr/bin/env node
// design-tokens/gen.mjs — codegen for the shared design-token + status SSOT.
//
// Reads the two source-of-truth JSON files (tokens.json, status.json) and emits
// five generated artifacts consumed by the two separate frontends:
//
//   web/ (Tailwind app; ships a CSS-variable light/dark theme layer)
//     - web/tailwind.preset.cjs        theme.extend colors/font/radius from tokens;
//                                      `cao.*` = fixed dark status colors (legacy),
//                                      `caoV.*` = var() refs into theme.generated.css
//     - web/src/status.generated.ts    STATUS_CONFIG / UNKNOWN_CONFIG (Tailwind classes)
//     - web/src/theme.generated.css    app/pastel/semantic pairs as CSS variables,
//                                      keyed on <html data-theme="dark|light">
//
//   cao_mcp_apps/ (host-themed, JIT-free, single-file in-host app)
//     - cao_mcp_apps/src/shared/tokens.generated.css   :root fallback == tokens
//     - cao_mcp_apps/src/shared/status.generated.ts     status -> {label,role,pulse}
//
// This is CODEGEN, not a runtime dependency: cao_mcp_apps gains zero runtime deps
// (protecting the JIT-free + size budgets) and web stays Tailwind-native. A CI
// parity guard re-runs this with `--check`, which regenerates in memory and fails
// (exit 1) if any committed artifact is stale.
//
// Usage:
//   node design-tokens/gen.mjs            # write all artifacts
//   node design-tokens/gen.mjs --check    # verify artifacts are up to date

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");

const tokens = JSON.parse(readFileSync(resolve(HERE, "tokens.json"), "utf8"));
const status = JSON.parse(readFileSync(resolve(HERE, "status.json"), "utf8"));

const HEADER_TS =
  "// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.\n" +
  "// Edit design-tokens/tokens.json or design-tokens/status.json, then run\n" +
  "// `node design-tokens/gen.mjs`. CI (`gen.mjs --check`) fails on drift.\n";

const HEADER_HASH =
  "/* @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.\n" +
  "   Edit design-tokens/tokens.json, then run `node design-tokens/gen.mjs`.\n" +
  "   CI (`gen.mjs --check`) fails on drift. */\n";

// Map each semantic role -> the Tailwind color key (web) and the CSS custom
// property (cao_mcp_apps). These two names are the only role wiring; everything
// else flows from color.role in tokens.json.
const ROLE_ORDER = ["success", "info", "accent", "warning", "danger", "neutral"];

function lightDark(pair) {
  return `light-dark(${pair.light}, ${pair.dark})`;
}

// --- web theme-variable wiring (theme.generated.css + caoV preset palette) ----
// Semantic status roles that get a `--<role>` + `--<role>-bg` variable. The
// `accent` role (purple) is deliberately omitted: `--accent` is the brand accent
// (color.app.accentStrong). The purple status accent stays reachable via the
// untouched `cao-accent` Tailwind color / cao_mcp_apps `--cao-status-accent`.
const SEMANTIC_ROLES = ["success", "info", "warning", "danger", "neutral"];
const PASTEL_ORDER = ["mint", "sky", "lilac", "peach", "lemon", "rose"];
// Agent-viz provider accent chips (Phase 4-C): `--prov-<id>-bg`/`-fg` per CLI
// provider (codex/claude/agy), consumed by providerAccent.ts. Fallback for
// unmapped providers is the existing neutral `--surface-3`/`--text-2` pair.
const PROVIDER_ORDER = ["codex", "claude", "agy"];
// Alpha for the soft `--<role>-bg` tint derived from the role color.
const SEMANTIC_BG_ALPHA = 0.14;

function hexToRgba(hex, alpha) {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// Ordered list of every theme-varying color variable: { name, light, dark }.
// Drives both theme.generated.css (concrete hex per theme) and the caoV Tailwind
// palette (var() references). Order here is the emit order in both artifacts.
function themeColorVars() {
  const c = tokens.color;
  const app = c.app;
  const role = c.role;
  const pastel = c.pastel;
  const out = [];
  const pair = (name, p) => out.push({ name, light: p.light, dark: p.dark });
  // app surfaces
  pair("--bg", app.background);
  pair("--surface", app.surface);
  pair("--surface-2", app.surface2);
  pair("--surface-3", app.surface3);
  // One step past --surface-3 for hover on a raised control. Without it, a button
  // whose base is --surface-3 had no darker/lighter step available and its hover
  // silently did nothing (both bg-gray-700 and hover:bg-gray-600 mapped to
  // --surface-3). Moves the same direction in both themes.
  pair("--surface-hover", app.surfaceHover);
  // borders
  pair("--border", c.border.primary);
  pair("--border-soft", app.borderSoft);
  // text (text-3 derives from the neutral role per spec)
  pair("--text", c.text.primary);
  pair("--text-2", c.text.secondary);
  pair("--text-3", role.neutral);
  // brand accent
  pair("--accent", app.accentStrong);
  pair("--accent-soft", app.accentSoft);
  pair("--accent-text", app.accentText);
  pair("--on-accent", app.onAccent);
  // semantic status roles + soft `-bg` companion
  for (const r of SEMANTIC_ROLES) {
    pair(`--${r}`, role[r]);
    out.push({
      name: `--${r}-bg`,
      light: hexToRgba(role[r].light, SEMANTIC_BG_ALPHA),
      dark: hexToRgba(role[r].dark, SEMANTIC_BG_ALPHA),
    });
  }
  // pastel chips: fill (`--p-<name>`) + ink (`--p-<name>-ink`)
  for (const p of PASTEL_ORDER) {
    pair(`--p-${p}`, pastel[p].bg);
    pair(`--p-${p}-ink`, pastel[p].ink);
  }
  // provider accent chips: bg + fg per CLI provider
  for (const p of PROVIDER_ORDER) {
    pair(`--prov-${p}-bg`, c.provider[p].bg);
    pair(`--prov-${p}-fg`, c.provider[p].fg);
  }
  return out;
}

// ---------------------------------------------------------------------------
// web/tailwind.preset.cjs
// ---------------------------------------------------------------------------
function genTailwindPreset() {
  const role = tokens.color.role;
  // `cao.*` is the legacy fixed-dark status palette: status colors use the .dark
  // variant (the web app's historical theme). Retained for backward compat.
  const caoColors = ROLE_ORDER.map(
    (r) => `      "${r}": "${role[r].dark}",`,
  ).join("\n");
  // `caoV.*` references the runtime CSS variables from theme.generated.css so new
  // (Phase 1b) components follow <html data-theme>. e.g. `bg-caoV-surface`.
  const caoVColors = themeColorVars()
    .map((v) => `          "${v.name.slice(2)}": "var(${v.name})",`)
    .join("\n");

  return (
    "// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.\n" +
    "// Edit design-tokens/tokens.json, then run `node design-tokens/gen.mjs`.\n" +
    "// CI (`gen.mjs --check`) fails on drift.\n" +
    "//\n" +
    "// Tailwind preset: the web app's theme is token-derived. Semantic status\n" +
    "// colors live under the `cao-*` color family (e.g. `text-cao-success`).\n" +
    "/** @type {import('tailwindcss').Config} */\n" +
    "module.exports = {\n" +
    "  theme: {\n" +
    "    extend: {\n" +
    "      colors: {\n" +
    "        cao: {\n" +
    caoColors +
    "\n" +
    "        },\n" +
    "        caoV: {\n" +
    caoVColors +
    "\n" +
    "        },\n" +
    "      },\n" +
    `      fontFamily: {\n` +
    `        sans: ${JSON.stringify(tokens.typography.fontSans.split(", "))},\n` +
    "      },\n" +
    "      fontWeight: {\n" +
    `        semibold: "${tokens.typography.fontWeightSemibold}",\n` +
    "      },\n" +
    "      borderRadius: {\n" +
    // `md`/`full` keep their historical 8px/999px values so existing `rounded-md`
    // / `rounded-full` utilities are unchanged. The 8px legacy chrome radius now
    // lives at radius.sm (radius.md is the new 12px design-scale medium).
    `        md: "${tokens.radius.sm}",\n` +
    `        full: "${tokens.radius.full}",\n` +
    "      },\n" +
    "    },\n" +
    "  },\n" +
    "};\n"
  );
}

// ---------------------------------------------------------------------------
// web/src/status.generated.ts
// ---------------------------------------------------------------------------
function genWebStatus() {
  const entries = Object.entries(status.statuses);
  const known = entries.filter(([k]) => k !== "unknown");
  const unknown = status.statuses.unknown;

  const configEntries = known
    .map(([key, s]) => {
      const role = s.semanticRole;
      const lines = [
        `  ${key.toUpperCase()}: {`,
        `    label: ${JSON.stringify(s.label)},`,
        `    dotClass: "bg-cao-${role}",`,
        `    bgClass: "bg-cao-${role}/10",`,
        `    textClass: "text-cao-${role}",`,
      ];
      if (s.pulse) lines.push("    pulse: true,");
      lines.push("  },");
      return lines.join("\n");
    })
    .join("\n");

  return (
    HEADER_TS +
    "//\n" +
    "// web StatusBadge config. Keys are UPPERCASE terminal statuses; classes are\n" +
    "// Tailwind utilities resolved against the `cao-*` colors in tailwind.preset.cjs.\n" +
    "\n" +
    "export interface StatusStyle {\n" +
    "  label: string;\n" +
    "  dotClass: string;\n" +
    "  bgClass: string;\n" +
    "  textClass: string;\n" +
    "  pulse?: boolean;\n" +
    "}\n" +
    "\n" +
    "export const STATUS_CONFIG: Record<string, StatusStyle> = {\n" +
    configEntries +
    "\n};\n" +
    "\n" +
    "export const UNKNOWN_CONFIG: StatusStyle = {\n" +
    `  label: ${JSON.stringify(unknown.label)},\n` +
    `  dotClass: "bg-cao-${unknown.semanticRole}",\n` +
    `  bgClass: "bg-cao-${unknown.semanticRole}/10",\n` +
    `  textClass: "text-cao-${unknown.semanticRole}",\n` +
    "};\n"
  );
}

// ---------------------------------------------------------------------------
// cao_mcp_apps/src/shared/tokens.generated.css
// ---------------------------------------------------------------------------
function genTokensCss() {
  const c = tokens.color;
  const lines = [];
  lines.push(HEADER_HASH);
  lines.push("");
  lines.push("/* :root fallback layer. Host CSS variables (SEP-1865 theming)");
  lines.push("   override these at runtime — these are defaults only. */");
  lines.push(":root {");
  // Chrome variables (consumed across styles.css).
  lines.push("  /* chrome */");
  lines.push(`  --color-background-primary: ${lightDark(c.background.primary)};`);
  lines.push(`  --color-background-secondary: ${lightDark(c.background.secondary)};`);
  lines.push(`  --color-background-danger: ${lightDark(c.background.danger)};`);
  lines.push(`  --color-background-info: ${lightDark(c.background.info)};`);
  lines.push(`  --color-text-primary: ${lightDark(c.text.primary)};`);
  lines.push(`  --color-text-secondary: ${lightDark(c.text.secondary)};`);
  lines.push(`  --color-text-danger: ${lightDark(c.text.danger)};`);
  lines.push(`  --color-text-info: ${lightDark(c.text.info)};`);
  lines.push(`  --color-border-primary: ${lightDark(c.border.primary)};`);
  lines.push(`  --color-border-info: ${lightDark(c.border.info)};`);
  lines.push(`  --font-sans: ${tokens.typography.fontSans};`);
  lines.push(`  --font-weight-semibold: ${tokens.typography.fontWeightSemibold};`);
  // cao's chrome radius is the legacy 8px, which now lives at radius.sm (radius.md
  // became the new 12px web design-scale medium). Sourcing from radius.sm keeps
  // this host-facing artifact byte-identical.
  lines.push(`  --border-radius-md: ${tokens.radius.sm};`);
  lines.push(`  --border-radius-full: ${tokens.radius.full};`);
  // Status semantic-role colors (host-overridable).
  lines.push("  /* status semantic roles */");
  for (const r of ROLE_ORDER) {
    lines.push(`  --cao-status-${r}: ${lightDark(c.role[r])};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// cao_mcp_apps/src/shared/status.generated.ts
// ---------------------------------------------------------------------------
function genMcpStatus() {
  const entries = Object.entries(status.statuses);
  const body = entries
    .map(([key, s]) => {
      return (
        `  ${JSON.stringify(key)}: { ` +
        `label: ${JSON.stringify(s.label)}, ` +
        `semanticRole: ${JSON.stringify(s.semanticRole)}, ` +
        `pulse: ${s.pulse ? "true" : "false"} },`
      );
    })
    .join("\n");

  return (
    HEADER_TS +
    "//\n" +
    "// cao_mcp_apps status semantics. Keys are lowercase terminal statuses. The\n" +
    "// `semanticRole` resolves to the `--cao-status-<role>` CSS variable (defined\n" +
    "// in tokens.generated.css, host-overridable). `pulse` drives the animation.\n" +
    "\n" +
    'export type SemanticRole =\n' +
    ROLE_ORDER.map((r) => `  | ${JSON.stringify(r)}`).join("\n") +
    ";\n" +
    "\n" +
    "export interface StatusSemantics {\n" +
    "  label: string;\n" +
    "  semanticRole: SemanticRole;\n" +
    "  pulse: boolean;\n" +
    "}\n" +
    "\n" +
    "export const STATUS: Record<string, StatusSemantics> = {\n" +
    body +
    "\n};\n" +
    "\n" +
    "/** The canonical set of known status keys (render/validation order). */\n" +
    "export const KNOWN_STATUSES: readonly string[] = Object.keys(STATUS);\n"
  );
}

// ---------------------------------------------------------------------------
// web/src/theme.generated.css
// ---------------------------------------------------------------------------
function genThemeCss() {
  const vars = themeColorVars();
  const emit = (theme, indent) =>
    vars.map((v) => `${indent}${v.name}: ${v[theme]};`).join("\n");

  // Theme-independent scale tokens (radius / spacing / z-index / panel). Emitted
  // once in a base :root so the theme-override blocks below only carry colors.
  const scale = [];
  scale.push("  /* radius */");
  for (const [k, v] of Object.entries(tokens.radius)) {
    scale.push(`  --radius-${k}: ${v};`);
  }
  scale.push("  /* spacing (numeric scale) */");
  for (const [k, v] of Object.entries(tokens.spacing)) {
    if (/^\d+$/.test(k)) scale.push(`  --space-${k}: ${v};`);
  }
  scale.push("  /* z-index */");
  for (const [k, v] of Object.entries(tokens.zIndex)) {
    scale.push(`  --z-${k}: ${v};`);
  }
  scale.push("  /* panel dimensions */");
  const panelVar = (k) => "--panel-" + k.replace(/([A-Z])/g, "-$1").toLowerCase();
  for (const [k, v] of Object.entries(tokens.panel)) {
    scale.push(`  ${panelVar(k)}: ${v}px;`);
  }

  return (
    HEADER_HASH +
    "\n" +
    '/* CAO web theme variables, keyed on <html data-theme="dark|light">.\n' +
    "   Cascade: :root is the light default; @media(prefers-color-scheme: dark)\n" +
    "   follows the OS when no explicit choice is set; the [data-theme] blocks win\n" +
    "   when theme.ts stamps the attribute. Only variables are declared here — no\n" +
    "   element styles — so importing this file changes nothing until consumed. */\n" +
    "\n" +
    ":root {\n" +
    "  /* scale tokens (theme-independent) */\n" +
    scale.join("\n") +
    "\n}\n" +
    "\n" +
    ":root {\n" +
    "  /* light theme (default) */\n" +
    emit("light", "  ") +
    "\n}\n" +
    "\n" +
    "@media (prefers-color-scheme: dark) {\n" +
    "  :root {\n" +
    emit("dark", "    ") +
    "\n  }\n" +
    "}\n" +
    "\n" +
    ':root[data-theme="dark"] {\n' +
    emit("dark", "  ") +
    "\n}\n" +
    "\n" +
    ':root[data-theme="light"] {\n' +
    emit("light", "  ") +
    "\n}\n"
  );
}

// ---------------------------------------------------------------------------
// driver
// ---------------------------------------------------------------------------
const ARTIFACTS = [
  { path: resolve(REPO, "web/tailwind.preset.cjs"), content: genTailwindPreset() },
  { path: resolve(REPO, "web/src/status.generated.ts"), content: genWebStatus() },
  { path: resolve(REPO, "web/src/theme.generated.css"), content: genThemeCss() },
  {
    path: resolve(REPO, "cao_mcp_apps/src/shared/tokens.generated.css"),
    content: genTokensCss(),
  },
  {
    path: resolve(REPO, "cao_mcp_apps/src/shared/status.generated.ts"),
    content: genMcpStatus(),
  },
];

const check = process.argv.includes("--check");
let stale = 0;

for (const { path, content } of ARTIFACTS) {
  const rel = relative(REPO, path);
  if (check) {
    let current = null;
    try {
      current = readFileSync(path, "utf8");
    } catch {
      current = null;
    }
    if (current !== content) {
      stale += 1;
      console.error(`STALE: ${rel}`);
    } else {
      console.log(`ok: ${rel}`);
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote: ${rel}`);
  }
}

if (check && stale > 0) {
  console.error(
    `\ngen.mjs --check: ${stale} stale artifact(s). Run \`node design-tokens/gen.mjs\` and commit.`,
  );
  process.exit(1);
}

console.log(
  check
    ? "gen.mjs --check: all artifacts up to date."
    : `gen.mjs: wrote ${ARTIFACTS.length} artifact(s).`,
);
