// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.
// Edit design-tokens/tokens.json, then run `node design-tokens/gen.mjs`.
// CI (`gen.mjs --check`) fails on drift.
//
// Tailwind preset: the web app's theme is token-derived. Semantic status
// colors live under the `cao-*` color family (e.g. `text-cao-success`).
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        cao: {
      "success": "#34d399",
      "info": "#60a5fa",
      "accent": "#c084fc",
      "warning": "#fbbf24",
      "danger": "#f87171",
      "neutral": "#a3a3a3",
        },
        caoV: {
          "bg": "var(--bg)",
          "surface": "var(--surface)",
          "surface-2": "var(--surface-2)",
          "surface-3": "var(--surface-3)",
          "surface-hover": "var(--surface-hover)",
          "border": "var(--border)",
          "border-soft": "var(--border-soft)",
          "text": "var(--text)",
          "text-2": "var(--text-2)",
          "text-3": "var(--text-3)",
          "accent": "var(--accent)",
          "accent-soft": "var(--accent-soft)",
          "accent-text": "var(--accent-text)",
          "on-accent": "var(--on-accent)",
          "success": "var(--success)",
          "success-bg": "var(--success-bg)",
          "info": "var(--info)",
          "info-bg": "var(--info-bg)",
          "warning": "var(--warning)",
          "warning-bg": "var(--warning-bg)",
          "danger": "var(--danger)",
          "danger-bg": "var(--danger-bg)",
          "neutral": "var(--neutral)",
          "neutral-bg": "var(--neutral-bg)",
          "p-mint": "var(--p-mint)",
          "p-mint-ink": "var(--p-mint-ink)",
          "p-sky": "var(--p-sky)",
          "p-sky-ink": "var(--p-sky-ink)",
          "p-lilac": "var(--p-lilac)",
          "p-lilac-ink": "var(--p-lilac-ink)",
          "p-peach": "var(--p-peach)",
          "p-peach-ink": "var(--p-peach-ink)",
          "p-lemon": "var(--p-lemon)",
          "p-lemon-ink": "var(--p-lemon-ink)",
          "p-rose": "var(--p-rose)",
          "p-rose-ink": "var(--p-rose-ink)",
          "prov-codex-bg": "var(--prov-codex-bg)",
          "prov-codex-fg": "var(--prov-codex-fg)",
          "prov-claude-bg": "var(--prov-claude-bg)",
          "prov-claude-fg": "var(--prov-claude-fg)",
          "prov-agy-bg": "var(--prov-agy-bg)",
          "prov-agy-fg": "var(--prov-agy-fg)",
        },
      },
      fontFamily: {
        sans: ["system-ui","-apple-system","sans-serif"],
      },
      fontWeight: {
        semibold: "600",
      },
      borderRadius: {
        md: "8px",
        full: "999px",
      },
    },
  },
};
